### PR TITLE
enable debug for packager

### PR DESCRIPTION
**Pull request by sillydong**
pass from ConnectionSettings.Debug

### CODE REVIEW

**Comment by AdamSLevy** [comment]
@sillydong Thank you for the contribution. Having a debug flag is a great addition to the code.

**Comment by AdamSLevy** [comment]
However there are a few things that I won't merge:
- Byte util functions aren't something I am interested in including with this package. They are helpful but they are easy enough for someone to implement in their own codebase. They go beyond the scope of this package. 
- On line 32 of Constants.go you have Chinese characters in the comments. I don't want Chinese characters in the package as I don't speak Chinese and don't know their meaning. If you wish to write Chinese documentation for this code base then I would be happy to link to it if it is complete. https://github.com/AdamSLevy/modbus/pull/1/files#diff-4baedf32b9291cb9bbcfc611b36e86b5R32
- On line 32 of Query.go you changed a limit from 125 to 258. This is incorrect. The specification limits the max number of registers that can be read to 125. https://github.com/AdamSLevy/modbus/pull/1/files#diff-2bba52eb867374d004d19ae60212bcfeR34 You can read the official specification here: http://www.modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf See section 6.3 on page 15

**Comment by AdamSLevy** [comment]
I cherry-picked out the commit for the Debug settings. I won't merge the other commits.

Thank you for the contribution!

**Comment by sillydong** [comment]
We have a device here which have an address of 0x100 of its registry. Check the following picture. I did some translation for Chinese characters. When I have an address of 0x100 and data length is 4 byte which means length of 2, I will have the max quantity 258.

wechatimg48

**Comment by AdamSLevy** [comment]
I suppose you must mean that you want to read something like more than 62
of these 4 byte (2 register) floats at a time. Because you certainly can
read that many using the code as is. If you mean that you need this to read
a single register of that type then you are mistaken. But I don't think
that's what you meant.

It's entirely possible that you are dealing with a non conformant
imolementation or custom tweak of the Modbus protocol, in which case having
flexibility in the library would be a good idea. I would be interested in
adding this as an packager option allowing the user to set whether this
Modbus package enforces strict length requirements.

I would prefer that over changing the constant value to something
non-officially conformant.

**Comment by sillydong** [comment]
Add an option can be a good idea. People may treat none standard protocol.

**Pull request closed without merging**
